### ISSUE TITLE
Lot of errors lead to "RuntimeError: maximum recursion depth exceeded"

### ISSUE THREAD

**Issue by agroppi** [fenderglass/Ragout#29]
I have launched ragout with the following recipe : 
```
.references = persica
.target = marouch

persica.fasta = references/persica.fasta
marouch.fasta = marouch_contigs.fasta
```
size of the genomes around 220 Mb

The first step with Sibelia runs perfectly. But then I have a lot of errors (see full log here attached)

Any idea of what's going wrong ?
[ragout_Marouch_vs_persica_92577.zip](https://github.com/fenderglass/Ragout/files/2200686/ragout_Marouch_vs_persica_92577.zip)

**Comment by agroppi** [comment]
Hello,
Here is the ragout ouput dir including the slurm script I have used to launch ragout.
Thanks for your help

[Marouch_ragout.zip](https://github.com/fenderglass/Ragout/files/2204842/Marouch_ragout.zip)

**Comment by fenderglass** [comment]
Hi,

Please try the latest version from the master branch - it should be fixed now. Looks like there was an unexpectedly large number of rearrangements between  the reference and target genomes.

Additionally, it seems like the genomes have 70% synteny block coverage on scale 500, but only 30% on scale 5000. Most likely, this is due to contig fragmentation. If your final assembly will be fragmented (or have many unplaced sequence), consider reducing synteny block size. You can do this by adding an extra parameter to the recipe file, for example:

    .blocks = 2000,500,100

**Comment by agroppi** [comment]
Hi,
Thank your very much for your help.
I have re launched the updatyed version Ragout according to your advices.
I'll keep you informed.

**Comment by agroppi** [comment]
Ragout worked perfectly :)
Thanks again
