### ISSUE TITLE
Multiple Assemblers

### ISSUE THREAD

**Issue by kokyriakidis** [fenderglass/Ragout#43]
Hello, could I use multiple assemblers like Masurca, Abyss etc, concat their contigs into one file and then use Ragout mapping this final file to the reference? Are there advantages to this approach? I am talking about de novo assembly with illumina reads only

**Comment by fenderglass** [comment]
Hi,

Ragout expects a single assembly without significant duplications as input - so the approach you have described will not work. What is your intuition of using a concatenate of multiple assemblies instead of selecting the best one and scaffold it using a reference? You can try to add other assemblies as extra draft references, but I doubt if will have any effect on the result, in case you have a good closely related reference.

Mikhail

**Comment by fenderglass** [comment]
Closed due to inactivity, feel free to reopen in case you have more questions.
